<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="St. Elisabeth Stiftung IT-Software">

    <!-- Die 3 Meta-Tags oben *müssen* zuerst im head stehen; jeglicher sonstiger head-Inhalt muss *nach* diesen Tags kommen -->
    <title>Bestellformular</title>

    <!-- Bootstrap -->
    <link href="assets/css/style.min.css" rel="stylesheet">

    <!-- Unterstützung für Media Queries und HTML5-Elemente in IE8 über HTML5 shim und Respond.js -->
    <!-- ACHTUNG: Respond.js funktioniert nicht, wenn du die Seite über file:// aufrufst -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    	<header>
			<div class="container-fluid foundation-header">
				<div class="row">
					<div id="bluefield">															
                        <div class="col-lg-3 offset-lg-9">
							<a href="https://www.st-elisabeth-stiftung.de/">
								<img id="logo" src="assets/img/ses_logo_white.svg" alt="Stiftungslogo"/>
							</a>
						</div>						
					</div>				
                        <div id="whitestripe">
                        </div>
                            <div class="coloredstripe">
                                <div></div>
                                <div></div>
                                <div></div>
                                <div></div>
                                <div></div>
                                <div></div>
                                <div></div>
                            </div>
                </div>
			</div>
		</header>
        <body>